### ISSUE TITLE
ie10, ie11 - не выполняется вход в личный кабинет

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-prof-sys-tools#62]
при вводе корректных логина и пароля (проверялось в остальных браузерах неоднократно) именно в ие11 и ие10 не выполняется вход, а обновляется страница, на которой находились перед входом

**Comment by Derevyanchenko** [comment]
Валидация не отрабатывает в ИЕ, ее  нужно переделывать под ие (тоесть полностью переписывать)

**Comment by LubaPM** [comment]
тут нужен Артем
